### ISSUE TITLE
SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified

### ISSUE THREAD

**Issue by dpreussler** [mattprecious/telescope#82]
is not usable on Android 14 anymore as of :

Runtime-registered broadcasts receivers must specify export behavior
Apps and services that target Android 14 and use [context-registered receivers](https://developer.android.com/guide/components/broadcasts#context-registered-receivers) are required to specify a flag to indicate whether or not the receiver should be exported to all other apps on the device: either RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED, respectively. This requirement helps protect apps from security vulnerabilities by leveraging the [features for these receivers introduced in Android 13](https://developer.android.com/about/versions/13/features#runtime-receivers).
https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

```
Fatal Exception: java.lang.SecurityException: com.soundcloud.android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
       at android.os.Parcel.createException(Parcel.java:3053)
       at android.os.Parcel.readException(Parcel.java:3036)
       at android.os.Parcel.readException(Parcel.java:2978)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6137)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1913)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1853)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1841)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:772)
       at com.mattprecious.telescope.TelescopeLayout.registerRequestCaptureReceiver(TelescopeLayout.java:593)
       at com.mattprecious.telescope.TelescopeLayout.trigger(TelescopeLayout.java:413)
```

**Comment by mattprecious** [comment]
Thanks! I'll try to take a look soon. PRs are welcome, though.

**Comment by dpreussler** [comment]
couldnt get the project to run... otherwise would have opened a PR 🙈 
change is quite simple, sth like that:

```
  private void registerRequestCaptureReceiver() {
    if (SDK_INT >= Build.VERSION_CODES.O) {
      getContext().registerReceiver(requestCaptureReceiver, requestCaptureFilter, RECEIVER_NOT_EXPORTED);
    } else {
      getContext().registerReceiver(requestCaptureReceiver, requestCaptureFilter);
    }
  }
```

**Comment by dpreussler** [comment]
@mattprecious  any idea when to get a new release?
